---
# tasks file for common

- name: Stop Apache 2
  # shell : service apache2 Stop
  service:
    state: stopped
    name: apache2

- name: Install common apt-packages
  package:
    name: "{{ item }}"
    state: latest
    update_cache: no
  with_items:
    - htop
    - telnet
    - net-tools
    - ntp
    - git

- name: Set timezone
  timezone:
    name: Asia/Tokyo

- name: Create app user
  user:
    name: app
