---
# tasks file for common

- name: Stop Apache 2
  # shell : service apache2 Stop
  service:
    state: stopped
    name: apache2

- name: Install common apt-packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - htop
    - telnet
    - net-tools
    - ntp
    - git

- name: Set timezone
  timezone:
    name: Europe/Paris

- name: Create app user
  user:
    name: app
    uid: 202
    group: app
    groups: app
    shell: /bin/bash
    comment: 'App User'

- name: Create app group
  group:
    name: app
    gid: 202