---
# tasks file for mysql


- name: Install
  apt:
    name: "{{ item }}"
    state: present
    cache_valid_time: 3600
  with_items:
    - mysql-server
    - python-mysqldb
#- name: passw user in mysql
- mysql_user:
    name: niki
    priv: '*.*:ALL, GRANT'
    state: present

- name: Create a new database
  mysql_db:
    name: devops
    state: present
