---
# tasks file for mysql


- name: Install
  apt:
    name: "{{ item }}"
    state: present
    cache_valid_time: 3600
  with_items:
    - mysql-server
    - python-mysqldb

- name: Start mysql
  service:
    name: mysql
    state: started
