################################################################################
# > Main playbook used to spin up and configure the entire infrastructure
#
# @author: Florian DAMBRINE <@Lowess>
################################################################################
---

- include: vm-create.yml
	when: "'{{provider}}' == 'insset'"
- include: aws-create.yml
	when: "'{{provider}}' == 'aws'"
- include: google-create.yml	
	when: "'{{provider}}' == 'google'"

- include: databases.yml
- include: webservers.yml
