################################################################################
# > Playbook used to configure webservers
#
# @author: <Your Name>
################################################################################
---

# TODO
- name: Configure webservers
  hosts: webserver
  become: yes

  roles: 
    - common
    - nginx
    - uwsgi
    - webapp
