---
#

- name: Installation Python Pip, Dev ...
  apt:
    state: present
    name: "{{item}}"
    cache_valid_time: 3600
    update_cache: yes
  with_items:
    - python-pip
    - build-essential
    - python-apt
    - python-dev

- name: Installation virtualenv, uwsgi...
  pip:
    state: present
    name: "{{item}}"
  with_items:
    - virtualenv
    - uwsgi
    - uwsgitop

#- name: Creation dossiers uwsgi
#  file:
#    path:
#    state: directory
#    mode: 0755

#- git:
#  repo: ''
#
#- name: ENV du virtualenv
#  pip:
#    virtualenv: ????
#
##source myprojectenv/bin/activate
#- name: Activate ENV
#?????????
#
#- name: Installation uWSGI, flask
#  pip:
#    name: "{{item}}"
#    virtualenv: ????
#  with_items:
#    - uwsgi
##    - flask
#- name: Installation uwsgi
#  apt:
#    state: present
#    name: python-uwsgi
#    cache_valid_time: 3600
#    update_cache: yes


### -------------- CORRECTION -------------------##


- name: Create the Uwsgi folders
  file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: root
    mode: '0755'
  with_items:
    - /etc/uwsgi
    - /etc/uwsgi/apps-available
    - /etc/uwsgi/apps-enabled
    - /var/log/uwsgi

- name: Deploy emperor startup script
  copy:
    src: emperor-initd
    dest: /etc/init.d/emperor
    mode: '0755'

- name: Enable and start emperor service
  service:
    state: started
    name: emperor
    enabled: yes
    pattern: 'uwsgi --emperor'

- name: Setup log rotation on Uwsgi log folder
  copy:
    src: uwsgi-logrotate
    dest: /etc/logrotate.d/uwsgi
mode: '0644'